# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Force a specific iOS version for compatibility
platform :ios, '15.1'

# Disable the new architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AIApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  # Add this line for react-native-config
  pod 'react-native-config', :path => '../node_modules/react-native-config'

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix for 'always_out_of_date' error
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
      
      # Remove script phases with 'always_out_of_date' option which isn't supported in older CocoaPods
      if target.respond_to?(:build_phases) && target.build_phases.respond_to?(:each)
        target.build_phases.each do |phase|
          if phase.respond_to?(:name) && phase.respond_to?(:type) && phase.type == :shell_script
            phase.shell_script = phase.shell_script.gsub(/--always-out-of-date/, '')
          end
        end
      end
    end
  end
end
